/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module betacpu_6 (
    input clk,
    input rst,
    input [3:0] button,
    output reg [15:0] column_1,
    output reg [15:0] column_2,
    output reg [15:0] column_3,
    output reg [15:0] column_4,
    output reg [3:0] comboinc,
    output reg [3:0] scoreinc
  );
  
  
  
  reg [15:0] inputALU_a;
  
  reg [15:0] inputALU_b;
  
  wire [16-1:0] M_game_alu_c;
  wire [3-1:0] M_game_alu_zvn;
  reg [16-1:0] M_game_alu_a;
  reg [16-1:0] M_game_alu_b;
  reg [6-1:0] M_game_alu_alufn_signal;
  alu_12 game_alu (
    .a(M_game_alu_a),
    .b(M_game_alu_b),
    .alufn_signal(M_game_alu_alufn_signal),
    .c(M_game_alu_c),
    .zvn(M_game_alu_zvn)
  );
  
  wire [1-1:0] M_clock_detector_out;
  reg [1-1:0] M_clock_detector_in;
  edge_detector_3 clock_detector (
    .clk(clk),
    .in(M_clock_detector_in),
    .out(M_clock_detector_out)
  );
  wire [1-1:0] M_slow_timer_0_value;
  counter_13 slow_timer_0 (
    .clk(clk),
    .rst(rst),
    .value(M_slow_timer_0_value)
  );
  wire [1-1:0] M_slow_timer_1_value;
  counter_14 slow_timer_1 (
    .clk(clk),
    .rst(rst),
    .value(M_slow_timer_1_value)
  );
  wire [1-1:0] M_slow_timer_2_value;
  counter_15 slow_timer_2 (
    .clk(clk),
    .rst(rst),
    .value(M_slow_timer_2_value)
  );
  wire [6-1:0] M_game_cu_alufn;
  wire [4-1:0] M_game_cu_ra;
  wire [4-1:0] M_game_cu_rb;
  wire [4-1:0] M_game_cu_rc;
  wire [2-1:0] M_game_cu_asel;
  wire [3-1:0] M_game_cu_bsel;
  wire [1-1:0] M_game_cu_we;
  wire [2-1:0] M_game_cu_wdsel;
  wire [2-1:0] M_game_cu_set_speed;
  wire [16-1:0] M_game_cu_combo_inc;
  wire [16-1:0] M_game_cu_score_inc;
  reg [4-1:0] M_game_cu_button;
  reg [16-1:0] M_game_cu_rb_fromreg;
  reg [2-1:0] M_game_cu_randgen;
  reg [1-1:0] M_game_cu_slow_clock_in;
  controlunit_16 game_cu (
    .clk(clk),
    .rst(rst),
    .button(M_game_cu_button),
    .rb_fromreg(M_game_cu_rb_fromreg),
    .randgen(M_game_cu_randgen),
    .slow_clock_in(M_game_cu_slow_clock_in),
    .alufn(M_game_cu_alufn),
    .ra(M_game_cu_ra),
    .rb(M_game_cu_rb),
    .rc(M_game_cu_rc),
    .asel(M_game_cu_asel),
    .bsel(M_game_cu_bsel),
    .we(M_game_cu_we),
    .wdsel(M_game_cu_wdsel),
    .set_speed(M_game_cu_set_speed),
    .combo_inc(M_game_cu_combo_inc),
    .score_inc(M_game_cu_score_inc)
  );
  wire [16-1:0] M_game_reg_out_a;
  wire [16-1:0] M_game_reg_out_b;
  wire [16-1:0] M_game_reg_column_1;
  wire [16-1:0] M_game_reg_column_2;
  wire [16-1:0] M_game_reg_column_3;
  wire [16-1:0] M_game_reg_column_4;
  reg [4-1:0] M_game_reg_ra;
  reg [4-1:0] M_game_reg_rb;
  reg [4-1:0] M_game_reg_rc;
  reg [1-1:0] M_game_reg_we;
  reg [16-1:0] M_game_reg_data;
  regfile_17 game_reg (
    .clk(clk),
    .rst(rst),
    .ra(M_game_reg_ra),
    .rb(M_game_reg_rb),
    .rc(M_game_reg_rc),
    .we(M_game_reg_we),
    .data(M_game_reg_data),
    .out_a(M_game_reg_out_a),
    .out_b(M_game_reg_out_b),
    .column_1(M_game_reg_column_1),
    .column_2(M_game_reg_column_2),
    .column_3(M_game_reg_column_3),
    .column_4(M_game_reg_column_4)
  );
  wire [2-1:0] M_randgen_out;
  random_row_18 randgen (
    .clk(clk),
    .rst(rst),
    .out(M_randgen_out)
  );
  
  always @* begin
    M_clock_detector_in = 1'h0;
    M_game_cu_slow_clock_in = 1'h0;
    if (M_game_cu_set_speed == 1'h1) begin
      M_clock_detector_in = M_slow_timer_0_value;
      M_game_cu_slow_clock_in = M_clock_detector_out;
    end else begin
      if (M_game_cu_set_speed == 2'h2) begin
        M_clock_detector_in = M_slow_timer_1_value;
        M_game_cu_slow_clock_in = M_clock_detector_out;
      end else begin
        if (M_game_cu_set_speed == 2'h3) begin
          M_clock_detector_in = M_slow_timer_2_value;
          M_game_cu_slow_clock_in = M_clock_detector_out;
        end
      end
    end
    column_1 = M_game_reg_column_1;
    column_2 = M_game_reg_column_2;
    column_3 = M_game_reg_column_3;
    column_4 = M_game_reg_column_4;
    comboinc = M_game_cu_combo_inc[0+3-:4];
    scoreinc = M_game_cu_score_inc[0+3-:4];
    M_game_cu_button = button;
    M_game_cu_randgen = M_randgen_out;
    M_game_reg_we = M_game_cu_we;
    M_game_reg_ra = M_game_cu_ra;
    M_game_reg_rb = M_game_cu_rb;
    M_game_reg_rc = M_game_cu_rc;
    M_game_cu_rb_fromreg = M_game_reg_out_b;
    
    case (M_game_cu_asel)
      2'h0: begin
        inputALU_a = M_game_reg_out_a;
      end
      2'h1: begin
        inputALU_a = 16'h0002;
      end
      2'h2: begin
        inputALU_a = 16'h0003;
      end
      default: begin
        inputALU_a = 1'h0;
      end
    endcase
    
    case (M_game_cu_bsel)
      3'h0: begin
        inputALU_b = M_game_reg_out_b;
      end
      3'h1: begin
        inputALU_b = 16'h00bf;
      end
      3'h2: begin
        inputALU_b = 16'h00df;
      end
      3'h3: begin
        inputALU_b = 16'h00ef;
      end
      3'h4: begin
        inputALU_b = 16'h0001;
      end
      3'h5: begin
        inputALU_b = 16'h0080;
      end
      3'h6: begin
        inputALU_b = 16'h0002;
      end
      3'h7: begin
        inputALU_b = 16'h0004;
      end
      default: begin
        inputALU_b = 1'h0;
      end
    endcase
    M_game_alu_a = inputALU_a;
    M_game_alu_b = inputALU_b;
    M_game_alu_alufn_signal = M_game_cu_alufn;
    
    case (M_game_cu_wdsel)
      2'h1: begin
        M_game_reg_data = 16'h0032;
      end
      2'h2: begin
        M_game_reg_data = 16'h0064;
      end
      2'h3: begin
        M_game_reg_data = 16'h00c8;
      end
      default: begin
        M_game_reg_data = M_game_alu_c;
      end
    endcase
  end
endmodule
