/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_22 (
    input [15:0] a,
    input [4:0] b,
    input [5:0] alufn_signal,
    output reg [15:0] c
  );
  
  
  
  always @* begin
    
    case (alufn_signal[0+1-:2])
      default: begin
        c = a;
      end
      2'h0: begin
        c = a << b;
      end
      2'h1: begin
        c = a >> b;
      end
      2'h3: begin
        c = $signed(a) >>> b;
      end
    endcase
  end
endmodule
